# Generated by Django 6.1 on 2026-08-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
